language: python
python:
- '3.5'
- '3.6'
install:
- pip install .[test]
script:
- pytest --cov=./
- codecov
deploy:
  provider: pypi
  user: line-mind
  password:
    secure: t37hcp/HcYzjt55BzLtLhyr2lQkoL+3covhaO5GEXM4aIvuxCNX+h3uAXkwTs0sZ1jFxcSLtbcgSF15Xm00A8lHnjEu9H7kspF7gB7DZG7nCI46vCUCnLJTXpvZnEalKut9cPjg0IMvtMmPQShxC6q7Le8AauSJ2wtUS+is0pQqOLMFtUOixx9ErzXobAMZw3AmeOAM/Z4b10k2x1q/yoPF7VrQFLvw2hSM/xHBTUWjYeNNDHwT+F/2Clt2h5xrZ0FAhuPZ3r0jiNUepr3jVt1glOUwq8GKbNuxFPDoEuba8/bkOZlIAEfaZC4pu3yYfPqlcG9zTsnfhc2OMeCCzkBBA020Rqui8uoujshHDtFh2njir611En86S+hbe9SOqlW0LBTYKVHQZUOsxHCaba+MsU/Q7er/9fjROQH4buxUhaOd6ReU4twSokSjoF53LuqNF/3CvNikaY6yWWuZyp16bEo+jQtZSKAM3zeubTX8bmXUoehkQgmOxmyzij7rkzI5S3I00qr+vWoNblWVb3bFiEKb1iQoEvYneUDv/aggRuIAW1sthcyT6aDrRUYnL+tVtL6OtGAOVoS5bgVBWrk1J350Tx5BuZX3K6Eu/lRZucvzkIZiVM0Tb5MEtfhuzk6ekW8waT87laOddrgUYZDeRyqJppdBTRSoeD443aQo=
  on:
    tags: true
