language: python
python:
- '3.5'
- '3.6'
install:
- pip install .[test]
script:
- pytest --cov=./
- codecov
deploy:
  provider: pypi
  user: line-mind
  on:
    branch: master
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: Blq8jj4+t1DAAqoo+zMTmLGoz0VkwDnhembOUiNySfI0h5C+4SHy/tdVBYBtqZjWoi0xwizVsOhDJq13+zRFAkKcnSLibICdioFuXnYigLcLI2sIYtEqeYDFKBBbcK6d/HM33BBGBOwdW5DS/W7IRzNskltrmnNq6nGtZrnaV4wlwtR7xm+tPl24l6F4zGPpdNagZ80/1m8mC5WXmIVBjtdCBcfGOrCZLoc6NDFBnLmnfYrvKBVa3UWKEHeQn1WaDFvvsMfiBPoak7hCxEt2NYX4x+CBJogAPNBQyjNWPKttwIqpHUiKDRI6gxdkBudmqc19m7HLk5acPyxMu9dFxFv8pHLIrl6ekiw5zhgkeP6eD41dAVl4sdsKghN8DyWLBuXpvQ9zlYzZaoD52UZ3B0tgQVQiWTWvgy45+lqBf2PoNGMr8HtkWTewK0T07dfgA/drudpngpnQyFthGKqZZehnDQjehFIPTPHwN+3EuWq6vOiYuuZ8p74LekwPTvpYSuBl9QHaipDrJKN/e2fNpIXNKMvLS4+f98PtxLq1O2MrtF+VzCTGNyfr4MwA5oW71rufqcrKsX4bNfL8Ab7P5UT8kMXJHJ7CcAHWGXB4IE07YWsAum27K4Q4fGyX9Ke4hRM3t2HJ8bwMb0k7sDzndpI6sAi3pnKE5j6J8MV8FzE=
