language: python
python:
- '3.5'
- '3.6'
install:
- pip install .[test]
script:
- pytest --cov=./
- codecov
deploy:
  provider: pypi
  user: line-mind
  password:
    secure: cA8ewcSTJFlkqsw9vXTA1QmuZTIP7iuj8eeB4ER3PCIiTqBTT2trto3h1zdVZPtpuFD0c6I8nxt97biyuHw3gsA6FgHYUR16NocdegxmwozANqg/shTuORzgPH8GF0xVTmw5xMMYs5JWVkwL3O6W7HxvGoozmPXaC3/T2wJ03CGdOh5g3oxYUwERKv/kSFBYTg0Nvlw5XO9T/4qHl25TM2uvxbm4Ve60+TyUtCwO+esLWUbQojkE6vO3VV7d4huXorzb2WkDgOka4wStbfThRIVxl1pSxyQvI6tbiDfm+Kg6E3IPG7iOnN4R1FIrYvrIu2NYFdpQ7LHDq7xLPiLZqoBqU3TzHoSV+3akoBSbwttrlPpk3xwv//RgsY0wty/jfJhbMp7Qi0JZL/gLGXKxCLstcBso/Ypru190DWeaBziBEP4Shkf1jXf8RgKaPnpuArTuNNfqxIUPn0raZ0/sN7UlnjA1uoTnOFXhkg/FVc2ZaOA8wTvO2ZQygVJyFOVjJVpTY/dun3piqvw/Sl3kMB1cfxNEN62smP/BlWKFeLktO4LS1rLtl4TjTOJlC6M6l8dggwxYAUV8COfJKi74GY9l5Ke9P+GNb7UAcXERtG8m+dMs40QlPMmh7us2bNm+F4AYTOCffEj9wDdWiCudMGl5/MdLsJJlFOaKN3rKKVA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: line-mind/plsxml
notifications:
  email: false
