language: python
python:
- '3.5'
- '3.6'
install:
- pip install .[test]
script:
- pytest --cov=./
- codecov
deploy:
  provider: pypi
  user: line-mind
  on:
    branch: master
    python: 3.6
    tags: true
  distributions: sdist bdist_wheel
  skip-cleanup: true
  password:
    secure: hOuiF3WYVqznmVxBZsXmaA0EG03aSO31/ZfWL15X2JPD/rYQkb3NqBUOl32qVySDtaPQLxSnBeUerckTzI2luwi2+I+TNS4AkD/r5s+PR601sgkD7u4pbJ+ph4fhmSFrzeO2STsWcEBEwQ4CQs91vMXLzB2LilI5ANjetVCAzs0+wyYZ9ZgCpwgWjriII9+6tj/vS5lG0tc2LaXiBP7TAzGN/mRDqRNRhl4Gv82LKtAOk1vhs2q0KBYYV82/IEUlf4Pp7JOXG9FGdVTCdDFXbX79V3VECNNrI3t4iBoG24TI4Uyf2uC0dv+6+HtRrieWtyjykB6/JfKguXiikNlI/jho0sXeimq1o8K1uLb9g4F7eIXESEX4kYb+NABWBzd550kgm9s+Wb+n+jOCAWPExskX6TMeae6PSYJNaMrnG8+BUjJIwH27KUuLV3YxYkS+F088wQE9YztTGx5fK8Tr0uLcBRlDXmwJOgAdS9+Dk28afE7YFDjxgoJLSeBj86RHRjBxar4Bh6nYKRfk8sXHpi5BwElNuIZl6B9tofepO28Gyo6ZXuLb282aUjQboXBvkMehDHt0KlFFlPTtZ15My0pBg6/DrdD1D+OM4Jh+10HfhyiO9KDFAC19eHTBS+RVi5hbCz+sW+gCkwph3NDyzjS8/5M4OX+MZSVx+0eNqYg=
